### ISSUE TITLE
Wrong default value 

### ISSUE THREAD

**Issue by gampleman** [MackeyRMS/json-decode-attempt#2]
```elm


datum =
    Enc.object
        [ ("bar", Enc.int 4)
        ]


sub =
    D.succeed identity
        |> D.required "bar" [] (D.intOr 3)


decoder =
    D.succeed identity
        |> D.required "foo" [] sub


result =
    D.decode decoder datum

-- produces

{ errors = [Failure "Expecting an OBJECT with a field named `foo`" <internals>]
, value = 4 -- not 3 as expected
}

```

https://ellie-app.com/rqsFjhY6WpQa1

This is caused by the implementation of `field`:

```field name (D decoder) =
    decoder
        |> Decode.andThen
            (\dec ->
                Decode.field name decoder
                    |> withDefault (Validated [] dec.value)
                    |> flatten
                    |> toDecoder
            )
        |> D
```

where the decoder is run without `Decode.field` in the wrong context order to get the default value. However if the decoder succeeds in that context, than an incorrect value is produced there.

I'd imagine this failure mode would be quite common when decoding tree data-structures.

**Comment by erlandsona** [comment]
Brought the example into the test suite, and got it passing with the updates we discussed on slack. v3 has the fix now. Thanks for catching this!
